title:            lourcastillo
tagline:          Just another blog
description:      Bug hunter and Mozilla Volunteer
canonical: https://lourcastillo.github.io

# Owner/author information
owner:
  name:           Lourdes Castillo
  avatar:         avatar.png
  bio:            "Mozilla Rep & QA Engineer"
  email:          lourdeslcastilloa@gmail.com
  twitter:        lourcastle
  github:         lourcastillo
  instagram:      lourcastillo
  location:       "Santiago, Chile"
  # Plug in your twitter shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/lourcastillo
    external: true
  - title: Mozillachile
    url: https://mozillachile.cl/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Santiago
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
